
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int dim = 18;
  public static final int function = 11;
  public static final int newline = 36;
  public static final int loop = 17;
  public static final int next = 16;
  public static final int If = 22;
  public static final int as = 19;
  public static final int write = 5;
  public static final int coma = 12;
  public static final int Else = 26;
  public static final int identificador = 34;
  public static final int oprel = 31;
  public static final int tipoparametro = 27;
  public static final int end = 13;
  public static final int opmult = 33;
  public static final int Return = 25;
  public static final int read = 6;
  public static final int While = 24;
  public static final int numero = 40;
  public static final int then = 14;
  public static final int For = 23;
  public static final int cerrarparentesis = 4;
  public static final int sub = 2;
  public static final int console = 7;
  public static final int EOF = 0;
  public static final int abrirparentesis = 3;
  public static final int error = 1;
  public static final int truefalse = 29;
  public static final int punto = 8;
  public static final int Do = 21;
  public static final int oplog = 30;
  public static final int not = 20;
  public static final int comentario = 39;
  public static final int tab = 37;
  public static final int espacio = 35;
  public static final int tipovar = 28;
  public static final int asignacion = 10;
  public static final int opsum = 32;
  public static final int to = 15;
  public static final int cadena = 38;
  public static final int type = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "sub",
  "abrirparentesis",
  "cerrarparentesis",
  "write",
  "read",
  "console",
  "punto",
  "type",
  "asignacion",
  "function",
  "coma",
  "end",
  "then",
  "to",
  "next",
  "loop",
  "dim",
  "as",
  "not",
  "Do",
  "If",
  "For",
  "While",
  "Return",
  "Else",
  "tipoparametro",
  "tipovar",
  "truefalse",
  "oplog",
  "oprel",
  "opsum",
  "opmult",
  "identificador",
  "espacio",
  "newline",
  "tab",
  "cadena",
  "comentario",
  "numero"
  };
}

