/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pc;

import pc.tabla.TablasDeSimbolos;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Denisse
 */
public class VentanaTablaSimbolos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTablaSimbolos
     */
    TablasDeSimbolos tablas_De_simbolos;

    public VentanaTablaSimbolos(TablasDeSimbolos tbs) {
        initComponents();
        this.tablas_De_simbolos = tbs;
        try {
            DefaultTableModel model1 = (DefaultTableModel) this.jt_tablasimbolos.getModel();
            for (int k = 0; k < tbs.tablas.size(); k++) {
                Object[] o1 = {tbs.tablas.get(k).name};
                model1.addRow(o1);
                for (int i = 0; i < tbs.tablas.get(k).get_ids().size(); i++) {
                    Object[] o = {tbs.tablas.get(k).get_ids().get(i).getId(),tbs.tablas.get(k).get_ids().get(i).getTipo().getName(),tbs.tablas.get(k).get_ids().get(i).getTipo().toString(), tbs.tablas.get(k).get_ids().get(i).getLinea(), tbs.tablas.get(k).get_ids().get(i).getColumna(),tbs.tablas.get(k).get_ids().get(i).getAmbito(),tbs.tablas.get(k).get_ids().get(i).getHijos()
                    ,tbs.tablas.get(k).get_ids().get(i).getOffset(),tbs.tablas.get(k).get_ids().get(i).isIsParametro(),tbs.tablas.get(k).get_ids().get(i).getTipoParametro()};

                    model1.addRow(o);
                }
                Object[] o2 = {""};
                model1.addRow(o2);
            }
            this.jt_tablasimbolos.setModel(model1);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tablasimbolos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jt_tablasimbolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo name", "Tipo", "Line", "Column", "Ambito", "Hijos", "Offset", "EsParametro", "TipoParametro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_tablasimbolos);
        if (jt_tablasimbolos.getColumnModel().getColumnCount() > 0) {
            jt_tablasimbolos.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_tablasimbolos;
    // End of variables declaration//GEN-END:variables
}
