
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 37;
  public static final int FUNCTION = 11;
  public static final int OPSUM = 36;
  public static final int FOR = 20;
  public static final int WRITE = 6;
  public static final int IDENTIFICADOR = 38;
  public static final int NOT = 31;
  public static final int TYPE = 10;
  public static final int TAB = 41;
  public static final int ESPACIO = 39;
  public static final int TIPOVAR = 29;
  public static final int TIPOPARAMETRO = 12;
  public static final int BEGIN = 15;
  public static final int OPREL = 33;
  public static final int UNTIL = 26;
  public static final int NEXT = 22;
  public static final int LOOP = 25;
  public static final int IF = 17;
  public static final int DIM = 27;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int CADENA = 42;
  public static final int COMENTARIO = 43;
  public static final int NEWLINE = 40;
  public static final int LINE = 5;
  public static final int ASIGNACION = 34;
  public static final int ABRIRPARENTESIS = 3;
  public static final int ELSE = 19;
  public static final int PUNTO = 9;
  public static final int READ = 7;
  public static final int TO = 21;
  public static final int WHILE = 24;
  public static final int THEN = 18;
  public static final int END = 16;
  public static final int CERRARPARENTESIS = 4;
  public static final int OPLOG = 32;
  public static final int AS = 28;
  public static final int TRUEFALSE = 30;
  public static final int SUB = 2;
  public static final int OPMULT = 35;
  public static final int DO = 23;
  public static final int CONSOLE = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUB",
  "ABRIRPARENTESIS",
  "CERRARPARENTESIS",
  "LINE",
  "WRITE",
  "READ",
  "CONSOLE",
  "PUNTO",
  "TYPE",
  "FUNCTION",
  "TIPOPARAMETRO",
  "COMA",
  "RETURN",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "FOR",
  "TO",
  "NEXT",
  "DO",
  "WHILE",
  "LOOP",
  "UNTIL",
  "DIM",
  "AS",
  "TIPOVAR",
  "TRUEFALSE",
  "NOT",
  "OPLOG",
  "OPREL",
  "ASIGNACION",
  "OPMULT",
  "OPSUM",
  "NUMERO",
  "IDENTIFICADOR",
  "ESPACIO",
  "NEWLINE",
  "TAB",
  "CADENA",
  "COMENTARIO"
  };
}

