
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyectocompi1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int dim = 22;
  public static final int function = 13;
  public static final int newline = 40;
  public static final int loop = 20;
  public static final int next = 19;
  public static final int If = 26;
  public static final int as = 23;
  public static final int write = 6;
  public static final int coma = 14;
  public static final int line = 5;
  public static final int Else = 30;
  public static final int identificador = 38;
  public static final int begin = 15;
  public static final int oprel = 35;
  public static final int until = 21;
  public static final int tipoparametro = 31;
  public static final int end = 16;
  public static final int opmult = 37;
  public static final int read = 7;
  public static final int Return = 29;
  public static final int While = 28;
  public static final int numero = 44;
  public static final int then = 17;
  public static final int sub = 2;
  public static final int For = 27;
  public static final int cerrarparentesis = 4;
  public static final int console = 8;
  public static final int EOF = 0;
  public static final int abrirparentesis = 3;
  public static final int error = 1;
  public static final int truefalse = 33;
  public static final int punto = 9;
  public static final int dospuntos = 12;
  public static final int Do = 25;
  public static final int oplog = 34;
  public static final int not = 24;
  public static final int comentario = 43;
  public static final int tab = 41;
  public static final int espacio = 39;
  public static final int tipovar = 32;
  public static final int asignacion = 11;
  public static final int opsum = 36;
  public static final int to = 18;
  public static final int cadena = 42;
  public static final int type = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "sub",
  "abrirparentesis",
  "cerrarparentesis",
  "line",
  "write",
  "read",
  "console",
  "punto",
  "type",
  "asignacion",
  "dospuntos",
  "function",
  "coma",
  "begin",
  "end",
  "then",
  "to",
  "next",
  "loop",
  "until",
  "dim",
  "as",
  "not",
  "Do",
  "If",
  "For",
  "While",
  "Return",
  "Else",
  "tipoparametro",
  "tipovar",
  "truefalse",
  "oplog",
  "oprel",
  "opsum",
  "opmult",
  "identificador",
  "espacio",
  "newline",
  "tab",
  "cadena",
  "comentario",
  "numero"
  };
}

